# Generated by Django 4.1.3 on 2022-12-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_upgrade_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='upgrade',
            field=models.CharField(choices=[('Yes', 'No'), ('Yes', 'No')], default='No', max_length=3),
        ),
    ]
