# Generated by Django 4.1.3 on 2022-12-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_order_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='upgrade',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
